##########Mapping US###########
use reisewarnung;
ALTER TABLE travel_advisories_us
ADD COLUMN Level_numeric INT;

-- Die neue Spalte mit den numerischen Werten basierend auf dem Mapping aktualisieren
UPDATE travel_advisories_us
SET Level_numeric = CASE
    WHEN Level = '1: Exercise normal precautions' THEN 1
    WHEN Level = '2: Exercise increased caution' THEN 2
    WHEN Level = '3: Reconsider travel' THEN 3
    WHEN Level = '4: Do not travel' THEN 4
    WHEN Level = 'Level 1: Exercise Normal Precautions' THEN 1
    WHEN Level = 'Level 4: Do Not Travel' THEN 4
    WHEN Level = 'Level 2: Exercise Increased Caution' THEN 2
    WHEN Level = 'Level 3: Reconsider Travel' THEN 3
    ELSE NULL -- Falls ein Level nicht im Mapping enthalten ist, wird NULL gesetzt
END;


##############AUS#############
use reisewarnung;
-- Neue Spalte 'Level_numeric' hinzufügen
ALTER TABLE travel_advisories_aus
ADD COLUMN Level_numeric INT;

-- Die neue Spalte mit den numerischen Werten basierend auf dem Mapping aktualisieren
UPDATE travel_advisories_aus
SET Level_numeric = CASE
    WHEN Level = 'Exercise normal safety precautions' THEN 1
    WHEN Level = 'Exercise a high degree of caution' THEN 2
    WHEN Level = 'Reconsider your need to travel' THEN 3
    WHEN Level = 'Do not travel' THEN 4
    ELSE NULL -- Falls ein Level nicht im Mapping enthalten ist, wird NULL gesetzt
END;



###########Canada##########
-- Neue Spalte 'Level_numeric' hinzufügen
ALTER TABLE travel_advisories_can
ADD COLUMN Level_numeric INT;

-- Die neue Spalte mit den numerischen Werten basierend auf dem Mapping aktualisieren
UPDATE travel_advisories_can
SET Level_numeric = CASE
    WHEN Level = 'AVOID ALL TRAVEL' THEN 4
    WHEN Level = 'Exercise normal security precautions; see also regional advisories.' THEN 1
    WHEN Level = 'Exercise a high degree of caution; see also regional advisories.' THEN 2
    WHEN Level = 'Exercise normal security precautions' THEN 1
    WHEN Level = 'Exercise a high degree of caution' THEN 2
    WHEN Level = 'AVOID ALL TRAVEL; see also regional advisories.' THEN 4
    WHEN Level = 'AVOID NON-ESSENTIAL TRAVEL; see also regional advisories.' THEN 3
    WHEN Level = 'AVOID NON-ESSENTIAL TRAVEL' THEN 3
    WHEN Level = 'Exercise normal security precautions (with regional advisories)' THEN 1
    WHEN Level = 'Exercise a high degree of caution (with regional advisories)' THEN 2
    WHEN Level = 'Avoid all travel (with regional advisories)' THEN 4
    WHEN Level = 'Avoid non-essential travel (with regional advisories)' THEN 3
    WHEN Level = 'Take normal security precautions (with regional advisories)' THEN 1
    WHEN Level = 'Take normal security precautions' THEN 1
    WHEN Level = 'Reconsider travel' THEN 3
    WHEN Level = 'Avoid all travel' THEN 4
    ELSE NULL -- Falls ein Level nicht im Mapping enthalten ist, wird NULL gesetzt
END;


#######Germany#########
ALTER TABLE travel_advisories_ger
ADD COLUMN Level_numeric INT;

-- Die neue Spalte mit den numerischen Werten basierend auf dem Mapping aktualisieren
UPDATE travel_advisories_ger
SET Level_numeric = CASE
    WHEN Warnung = 'Teilreisewarnung' THEN 4
    WHEN Warnung = 'Reisewarnung' THEN 3
    WHEN Warnung = 'None' THEN 1
    ELSE NULL -- Falls ein Level nicht im Mapping enthalten ist, wird NULL gesetzt
END;
COMMIT;


############Mapping############
-- Neue Spalte 'Country_ISO' hinzufügen (falls noch nicht vorhanden)
ALTER TABLE travel_advisories_us ADD COLUMN Country_ISO VARCHAR(3);
ALTER TABLE travel_advisories_aus ADD COLUMN Country_ISO VARCHAR(3);
ALTER TABLE travel_advisories_can ADD COLUMN Country_ISO VARCHAR(3);



###############US###############
-- Die Spalte 'Country_ISO' basierend auf der Spalte 'Country' in 'travel_advisories_us' aktualisieren
UPDATE travel_advisories_us
SET Country_ISO = CASE
    WHEN Country IN ('Afghanistan') THEN 'AFG'
    WHEN Country IN ('Albania') THEN 'ALB'
    WHEN Country IN ('Algeria') THEN 'DZA'
    WHEN Country IN ('Andorra') THEN 'AND'
    WHEN Country IN ('Angola') THEN 'AGO'
    WHEN Country IN ('AntiguaandBarbuda') THEN 'ATG'
    WHEN Country IN ('Argentina') THEN 'ARG'
    WHEN Country IN ('Armenia') THEN 'ARM'
    WHEN Country IN ('Australia', 'AUS') THEN 'AUS'
    WHEN Country IN ('Austria', 'Österreich') THEN 'AUT'
    WHEN Country IN ('Azerbaijan') THEN 'AZE'
    WHEN Country IN ('Bahamas') THEN 'BHS'
    WHEN Country IN ('Bahrain') THEN 'BHR'
    WHEN Country IN ('Bangladesh') THEN 'BGD'
    WHEN Country IN ('Barbados') THEN 'BRB'
    WHEN Country IN ('Belarus') THEN 'BLR'
    WHEN Country IN ('Belgium', 'België', 'Belgique') THEN 'BEL'
    WHEN Country IN ('Belize') THEN 'BLZ'
    WHEN Country IN ('Benin') THEN 'BEN'
    WHEN Country IN ('Bhutan') THEN 'BTN'
    WHEN Country IN ('Bolivia') THEN 'BOL'
    WHEN Country IN ('BosniaandHerzegovina') THEN 'BIH'
    WHEN Country IN ('Botswana') THEN 'BWA'
    WHEN Country IN ('Brazil', 'Brasil') THEN 'BRA'
    WHEN Country IN ('Brunei') THEN 'BRN'
    WHEN Country IN ('Bulgaria') THEN 'BGR'
    WHEN Country IN ('BurkinaFaso') THEN 'BFA'
    WHEN Country IN ('Burundi') THEN 'BDI'
    WHEN Country IN ('CaboVerde') THEN 'CPV'
    WHEN Country IN ('Cambodia') THEN 'KHM'
    WHEN Country IN ('Cameroon') THEN 'CMR'
    WHEN Country IN ('Canada', 'CAN') THEN 'CAN'
    WHEN Country IN ('CentralAfricanRepublic') THEN 'CAF'
    WHEN Country IN ('Chad') THEN 'TCD'
    WHEN Country IN ('Chile') THEN 'CHL'
    WHEN Country IN ('China', 'CN', 'PRC') THEN 'CHN'
    WHEN Country IN ('Colombia') THEN 'COL'
    WHEN Country IN ('Comoros') THEN 'COM'
    WHEN Country IN ('Congo(Congo-Brazzaville)') THEN 'COG'
    WHEN Country IN ('CostaRica') THEN 'CRI'
    WHEN Country IN ('Croatia', 'Hrvatska') THEN 'HRV'
    WHEN Country IN ('Cuba') THEN 'CUB'
    WHEN Country IN ('Cyprus') THEN 'CYP'
    WHEN Country IN ('CzechRepublic', 'Czechia', 'Českárepublika') THEN 'CZE'
    WHEN Country IN ('DemocraticRepublicoftheCongo') THEN 'COD'
    WHEN Country IN ('Denmark', 'Danmark') THEN 'DNK'
    WHEN Country IN ('Djibouti') THEN 'DJI'
    WHEN Country IN ('Dominica') THEN 'DMA'
    WHEN Country IN ('DominicanRepublic') THEN 'DOM'
    WHEN Country IN ('Ecuador') THEN 'ECU'
    WHEN Country IN ('Egypt') THEN 'EGY'
    WHEN Country IN ('ElSalvador') THEN 'SLV'
    WHEN Country IN ('EquatorialGuinea') THEN 'GNQ'
    WHEN Country IN ('Eritrea') THEN 'ERI'
    WHEN Country IN ('Estonia') THEN 'EST'
    WHEN Country IN ('Eswatini', 'Swaziland') THEN 'SWZ'
    WHEN Country IN ('Ethiopia') THEN 'ETH'
    WHEN Country IN ('Fiji') THEN 'FJI'
    WHEN Country IN ('Finland', 'Suomi') THEN 'FIN'
    WHEN Country IN ('France', 'Francia') THEN 'FRA'
    WHEN Country IN ('Gabon') THEN 'GAB'
    WHEN Country IN ('Gambia') THEN 'GMB'
    WHEN Country IN ('Georgia') THEN 'GEO'
    WHEN Country IN ('Germany', 'Deutschland') THEN 'DEU'
    WHEN Country IN ('Ghana') THEN 'GHA'
    WHEN Country IN ('Greece', 'Hellas') THEN 'GRC'
    WHEN Country IN ('Grenada') THEN 'GRD'
    WHEN Country IN ('Guatemala') THEN 'GTM'
    WHEN Country IN ('Guinea') THEN 'GIN'
    WHEN Country IN ('Guinea-Bissau') THEN 'GNB'
    WHEN Country IN ('Guyana') THEN 'GUY'
    WHEN Country IN ('Haiti') THEN 'HTI'
    WHEN Country IN ('Honduras') THEN 'HND'
    WHEN Country IN ('Hungary', 'Magyarország') THEN 'HUN'
    WHEN Country IN ('Iceland', 'Ísland') THEN 'ISL'
    WHEN Country IN ('India') THEN 'IND'
    WHEN Country IN ('Indonesia') THEN 'IDN'
    WHEN Country IN ('Iran') THEN 'IRN'
    WHEN Country IN ('Iraq') THEN 'IRQ'
    WHEN Country IN ('Ireland', 'Éire') THEN 'IRL'
    WHEN Country IN ('Israel') THEN 'ISR'
    WHEN Country IN ('Italy', 'Italia') THEN 'ITA'
    WHEN Country IN ('Jamaica') THEN 'JAM'
    WHEN Country IN ('Japan', 'Nippon') THEN 'JPN'
    WHEN Country IN ('Jordan') THEN 'JOR'
    WHEN Country IN ('Kazakhstan') THEN 'KAZ'
    WHEN Country IN ('Kenya') THEN 'KEN'
    WHEN Country IN ('Kiribati') THEN 'KIR'
    WHEN Country IN ('Korea,North', 'NorthKorea', 'DPRK') THEN 'PRK'
    WHEN Country IN ('Korea,South', 'SouthKorea', 'ROK') THEN 'KOR'
    WHEN Country IN ('Kuwait') THEN 'KWT'
    WHEN Country IN ('Kyrgyzstan') THEN 'KGZ'
    WHEN Country IN ('Laos') THEN 'LAO'
    WHEN Country IN ('Latvia') THEN 'LVA'
    WHEN Country IN ('Lebanon') THEN 'LBN'
    WHEN Country IN ('Lesotho') THEN 'LSO'
    WHEN Country IN ('Liberia') THEN 'LBR'
    WHEN Country IN ('Libya') THEN 'LBY'
    WHEN Country IN ('Liechtenstein') THEN 'LIE'
    WHEN Country IN ('Lithuania') THEN 'LTU'
    WHEN Country IN ('Luxembourg') THEN 'LUX'
    WHEN Country IN ('Madagascar') THEN 'MDG'
    WHEN Country IN ('Malawi') THEN 'MWI'
    WHEN Country IN ('Malaysia') THEN 'MYS'
    WHEN Country IN ('Maldives') THEN 'MDV'
    WHEN Country IN ('Mali') THEN 'MLI'
    WHEN Country IN ('Malta') THEN 'MLT'
    WHEN Country IN ('MarshallIslands') THEN 'MHL'
    WHEN Country IN ('Mauritania') THEN 'MRT'
    WHEN Country IN ('Mauritius') THEN 'MUS'
    WHEN Country IN ('Mexico') THEN 'MEX'
    WHEN Country IN ('Micronesia') THEN 'FSM'
    WHEN Country IN ('Moldova') THEN 'MDA'
    WHEN Country IN ('Monaco') THEN 'MCO'
    WHEN Country IN ('Mongolia') THEN 'MNG'
    WHEN Country IN ('Montenegro') THEN 'MNE'
    WHEN Country IN ('Morocco') THEN 'MAR'
    WHEN Country IN ('Mozambique') THEN 'MOZ'
    WHEN Country IN ('Myanmar', 'Burma') THEN 'MMR'
    WHEN Country IN ('Namibia') THEN 'NAM'
    WHEN Country IN ('Nauru') THEN 'NRU'
    WHEN Country IN ('Nepal') THEN 'NPL'
    WHEN Country IN ('Netherlands', 'Nederland') THEN 'NLD'
    WHEN Country IN ('NewZealand') THEN 'NZL'
    WHEN Country IN ('Nicaragua') THEN 'NIC'
    WHEN Country IN ('Niger') THEN 'NER'
    WHEN Country IN ('Nigeria') THEN 'NGA'
    WHEN Country IN ('NorthMacedonia') THEN 'MKD'
    WHEN Country IN ('Norway', 'Norge') THEN 'NOR'
    WHEN Country IN ('Oman') THEN 'OMN'
    WHEN Country IN ('Pakistan') THEN 'PAK'
    WHEN Country IN ('Palau') THEN 'PLW'
    WHEN Country IN ('Panama') THEN 'PAN'
    WHEN Country IN ('PapuaNewGuinea') THEN 'PNG'
    WHEN Country IN ('Paraguay') THEN 'PRY'
    WHEN Country IN ('Peru') THEN 'PER'
    WHEN Country IN ('Philippines') THEN 'PHL'
    WHEN Country IN ('Poland', 'Polska') THEN 'POL'
    WHEN Country IN ('Portugal') THEN 'PRT'
    WHEN Country IN ('Qatar') THEN 'QAT'
    WHEN Country IN ('Romania') THEN 'ROU'
    WHEN Country IN ('Russia', 'RussianFederation', 'RU') THEN 'RUS'
    WHEN Country IN ('Rwanda') THEN 'RWA'
    WHEN Country IN ('SaintKittsandNevis') THEN 'KNA'
    WHEN Country IN ('SaintLucia') THEN 'LCA'
    WHEN Country IN ('SaintVincentandtheGrenadines') THEN 'VCT'
    WHEN Country IN ('Samoa') THEN 'WSM'
    WHEN Country IN ('SanMarino') THEN 'SMR'
    WHEN Country IN ('SaoTomeandPrincipe') THEN 'STP'
    WHEN Country IN ('SaudiArabia') THEN 'SAU'
    WHEN Country IN ('Senegal') THEN 'SEN'
    WHEN Country IN ('Serbia') THEN 'SRB'
    WHEN Country IN ('Seychelles') THEN 'SYC'
    WHEN Country IN ('SierraLeone') THEN 'SLE'
    WHEN Country IN ('Singapore') THEN 'SGP'
    WHEN Country IN ('Slovakia') THEN 'SVK'
    WHEN Country IN ('Slovenia') THEN 'SVN'
    WHEN Country IN ('SolomonIslands') THEN 'SLB'
    WHEN Country IN ('Somalia') THEN 'SOM'
    WHEN Country IN ('SouthAfrica') THEN 'ZAF'
    WHEN Country IN ('SouthSudan') THEN 'SSD'
    WHEN Country IN ('Spain', 'España') THEN 'ESP'
    WHEN Country IN ('SriLanka') THEN 'LKA'
    WHEN Country IN ('Sudan') THEN 'SDN'
    WHEN Country IN ('Suriname') THEN 'SUR'
    WHEN Country IN ('Sweden', 'Sverige') THEN 'SWE'
    WHEN Country IN ('Switzerland', 'Suisse', 'Schweiz') THEN 'CHE'
    WHEN Country IN ('Syria') THEN 'SYR'
    WHEN Country IN ('Taiwan', 'TWN') THEN 'TWN'
    WHEN Country IN ('Tajikistan') THEN 'TJK'
    WHEN Country IN ('Tanzania') THEN 'TZA'
    WHEN Country IN ('Thailand') THEN 'THA'
    WHEN Country IN ('Timor-Leste') THEN 'TLS'
    WHEN Country IN ('Togo') THEN 'TGO'
    WHEN Country IN ('Tonga') THEN 'TON'
    WHEN Country IN ('TrinidadandTobago') THEN 'TTO'
    WHEN Country IN ('Tunisia') THEN 'TUN'
    WHEN Country IN ('Turkey') THEN 'TUR'
    WHEN Country IN ('Turkmenistan') THEN 'TKM'
    WHEN Country IN ('Tuvalu') THEN 'TUV'
    WHEN Country IN ('Uganda') THEN 'UGA'
    WHEN Country IN ('Ukraine') THEN 'UKR'
    WHEN Country IN ('UnitedArabEmirates') THEN 'ARE'
    WHEN Country IN ('UnitedKingdom', 'UK', 'Britain', 'England') THEN 'GBR'
    WHEN Country IN ('UnitedStates', 'USA', 'US') THEN 'USA'
    WHEN Country IN ('Uruguay') THEN 'URY'
    WHEN Country IN ('Uzbekistan') THEN 'UZB'
    WHEN Country IN ('Vanuatu') THEN 'VUT'
    WHEN Country IN ('VaticanCity', 'HolySee') THEN 'VAT'
    WHEN Country IN ('Venezuela') THEN 'VEN'
    WHEN Country IN ('Vietnam') THEN 'VNM'
    WHEN Country IN ('Yemen') THEN 'YEM'
    WHEN Country IN ('Zambia') THEN 'ZMB'
    WHEN Country IN ('Zimbabwe') THEN 'ZWE'
    WHEN Country IN ('CentralAfricanRepublic(CAR)') THEN 'CAF'
    WHEN Country IN ('DomincanRepublic') THEN 'DOM'
    WHEN Country IN ('HongKong') THEN 'HKG'
    WHEN Country IN ('Kosovo') THEN 'XKX'
    WHEN Country IN ('Zimbabwe') THEN 'ZWE'
    WHEN Country IN ("NorthKorea(DemocraticPeople'sRepublicofKorea)") THEN 'ZWE'
    WHEN Country IN ('TheGambia') THEN 'GMB'
    WHEN Country IN ('Anguilla') THEN 'AIA'
    WHEN Country IN ('UnitedArabEmirates(UAE)') THEN 'ARE'
    WHEN Country IN ('RepublicoftheCongo') THEN 'COD'
    WHEN Country IN ('Burma(Myanmar)') THEN 'MMR'
    WHEN Country IN ('Israel,TheWestBankandGaza') THEN 'ISR'
    WHEN Country IN ('Zimbabwe') THEN 'ZWE'
    ELSE NULL -- Falls kein Mapping vorhanden ist
END;



####Autralia####
UPDATE travel_advisories_aus
SET Country_ISO = CASE
    WHEN Country IN ('Afghanistan') THEN 'AFG'
    WHEN Country IN ('Albania') THEN 'ALB'
    WHEN Country IN ('Algeria') THEN 'DZA'
    WHEN Country IN ('Andorra') THEN 'AND'
    WHEN Country IN ('Angola') THEN 'AGO'
    WHEN Country IN ('Antigua and Barbuda') THEN 'ATG'
    WHEN Country IN ('Argentina') THEN 'ARG'
    WHEN Country IN ('Armenia') THEN 'ARM'
    WHEN Country IN ('Australia', 'AUS') THEN 'AUS'
    WHEN Country IN ('Austria', 'Österreich') THEN 'AUT'
    WHEN Country IN ('Azerbaijan') THEN 'AZE'
    WHEN Country IN ('Bahamas') THEN 'BHS'
    WHEN Country IN ('Bahrain') THEN 'BHR'
    WHEN Country IN ('Bangladesh') THEN 'BGD'
    WHEN Country IN ('Barbados') THEN 'BRB'
    WHEN Country IN ('Belarus') THEN 'BLR'
    WHEN Country IN ('Belgium', 'België', 'Belgique') THEN 'BEL'
    WHEN Country IN ('Belize') THEN 'BLZ'
    WHEN Country IN ('Benin') THEN 'BEN'
    WHEN Country IN ('Bhutan') THEN 'BTN'
    WHEN Country IN ('Bolivia') THEN 'BOL'
    WHEN Country IN ('Bosnia and Herzegovina') THEN 'BIH'
    WHEN Country IN ('Botswana') THEN 'BWA'
    WHEN Country IN ('Brazil', 'Brasil') THEN 'BRA'
    WHEN Country IN ('Brunei') THEN 'BRN'
    WHEN Country IN ('Bulgaria') THEN 'BGR'
    WHEN Country IN ('Burkina Faso') THEN 'BFA'
    WHEN Country IN ('Burundi') THEN 'BDI'
    WHEN Country IN ('Cabo Verde') THEN 'CPV'
    WHEN Country IN ('Cambodia') THEN 'KHM'
    WHEN Country IN ('Cameroon') THEN 'CMR'
    WHEN Country IN ('Canada', 'CAN') THEN 'CAN'
    WHEN Country IN ('Central African Republic') THEN 'CAF'
    WHEN Country IN ('Chad') THEN 'TCD'
    WHEN Country IN ('Chile') THEN 'CHL'
    WHEN Country IN ('China', 'CN', 'PRC') THEN 'CHN'
    WHEN Country IN ('Colombia') THEN 'COL'
    WHEN Country IN ('Comoros') THEN 'COM'
    WHEN Country IN ('Congo (Congo-Brazzaville)') THEN 'COG'
    WHEN Country IN ('Costa Rica') THEN 'CRI'
    WHEN Country IN ('Croatia', 'Hrvatska') THEN 'HRV'
    WHEN Country IN ('Cuba') THEN 'CUB'
    WHEN Country IN ('Cyprus') THEN 'CYP'
    WHEN Country IN ('Czech Republic', 'Czechia', 'Česká republika') THEN 'CZE'
    WHEN Country IN ('Democratic Republic of the Congo') THEN 'COD'
    WHEN Country IN ('Denmark', 'Danmark') THEN 'DNK'
    WHEN Country IN ('Djibouti') THEN 'DJI'
    WHEN Country IN ('Dominica') THEN 'DMA'
    WHEN Country IN ('Dominican Republic') THEN 'DOM'
    WHEN Country IN ('Ecuador') THEN 'ECU'
    WHEN Country IN ('Egypt') THEN 'EGY'
    WHEN Country IN ('El Salvador') THEN 'SLV'
    WHEN Country IN ('Equatorial Guinea') THEN 'GNQ'
    WHEN Country IN ('Eritrea') THEN 'ERI'
    WHEN Country IN ('Estonia') THEN 'EST'
    WHEN Country IN ('Eswatini', 'Swaziland') THEN 'SWZ'
    WHEN Country IN ('Ethiopia') THEN 'ETH'
    WHEN Country IN ('Fiji') THEN 'FJI'
    WHEN Country IN ('Finland', 'Suomi') THEN 'FIN'
    WHEN Country IN ('France', 'Francia') THEN 'FRA'
    WHEN Country IN ('Gabon') THEN 'GAB'
    WHEN Country IN ('Gambia') THEN 'GMB'
    WHEN Country IN ('Georgia') THEN 'GEO'
    WHEN Country IN ('Germany', 'Deutschland') THEN 'DEU'
    WHEN Country IN ('Ghana') THEN 'GHA'
    WHEN Country IN ('Greece', 'Hellas') THEN 'GRC'
    WHEN Country IN ('Grenada') THEN 'GRD'
    WHEN Country IN ('Guatemala') THEN 'GTM'
    WHEN Country IN ('Guinea') THEN 'GIN'
    WHEN Country IN ('Guinea-Bissau') THEN 'GNB'
    WHEN Country IN ('Guyana') THEN 'GUY'
    WHEN Country IN ('Haiti') THEN 'HTI'
    WHEN Country IN ('Honduras') THEN 'HND'
    WHEN Country IN ('Hungary', 'Magyarország') THEN 'HUN'
    WHEN Country IN ('Iceland', 'Ísland') THEN 'ISL'
    WHEN Country IN ('India') THEN 'IND'
    WHEN Country IN ('Indonesia') THEN 'IDN'
    WHEN Country IN ('Iran') THEN 'IRN'
    WHEN Country IN ('Iraq') THEN 'IRQ'
    WHEN Country IN ('Ireland', 'Éire') THEN 'IRL'
    WHEN Country IN ('Israel') THEN 'ISR'
    WHEN Country IN ('Italy', 'Italia') THEN 'ITA'
    WHEN Country IN ('Jamaica') THEN 'JAM'
    WHEN Country IN ('Japan', 'Nippon') THEN 'JPN'
    WHEN Country IN ('Jordan') THEN 'JOR'
    WHEN Country IN ('Kazakhstan') THEN 'KAZ'
    WHEN Country IN ('Kenya') THEN 'KEN'
    WHEN Country IN ('Kiribati') THEN 'KIR'
    WHEN Country IN ('Korea, North', 'North Korea', 'DPRK') THEN 'PRK'
    WHEN Country IN ('Korea, South', 'South Korea', 'ROK') THEN 'KOR'
    WHEN Country IN ('Kuwait') THEN 'KWT'
    WHEN Country IN ('Kyrgyzstan') THEN 'KGZ'
    WHEN Country IN ('Laos') THEN 'LAO'
    WHEN Country IN ('Latvia') THEN 'LVA'
    WHEN Country IN ('Lebanon') THEN 'LBN'
    WHEN Country IN ('Lesotho') THEN 'LSO'
    WHEN Country IN ('Liberia') THEN 'LBR'
    WHEN Country IN ('Libya') THEN 'LBY'
    WHEN Country IN ('Liechtenstein') THEN 'LIE'
    WHEN Country IN ('Lithuania') THEN 'LTU'
    WHEN Country IN ('Luxembourg') THEN 'LUX'
    WHEN Country IN ('Madagascar') THEN 'MDG'
    WHEN Country IN ('Malawi') THEN 'MWI'
    WHEN Country IN ('Malaysia') THEN 'MYS'
    WHEN Country IN ('Maldives') THEN 'MDV'
    WHEN Country IN ('Mali') THEN 'MLI'
    WHEN Country IN ('Malta') THEN 'MLT'
    WHEN Country IN ('Marshall Islands') THEN 'MHL'
    WHEN Country IN ('Mauritania') THEN 'MRT'
    WHEN Country IN ('Mauritius') THEN 'MUS'
    WHEN Country IN ('Mexico') THEN 'MEX'
    WHEN Country IN ('Micronesia') THEN 'FSM'
    WHEN Country IN ('Moldova') THEN 'MDA'
    WHEN Country IN ('Monaco') THEN 'MCO'
    WHEN Country IN ('Mongolia') THEN 'MNG'
    WHEN Country IN ('Montenegro') THEN 'MNE'
    WHEN Country IN ('Morocco') THEN 'MAR'
    WHEN Country IN ('Mozambique') THEN 'MOZ'
    WHEN Country IN ('Myanmar', 'Burma') THEN 'MMR'
    WHEN Country IN ('Namibia') THEN 'NAM'
    WHEN Country IN ('Nauru') THEN 'NRU'
    WHEN Country IN ('Nepal') THEN 'NPL'
    WHEN Country IN ('Netherlands', 'Nederland') THEN 'NLD'
    WHEN Country IN ('New Zealand') THEN 'NZL'
    WHEN Country IN ('Nicaragua') THEN 'NIC'
    WHEN Country IN ('Niger') THEN 'NER'
    WHEN Country IN ('Nigeria') THEN 'NGA'
    WHEN Country IN ('North Macedonia') THEN 'MKD'
    WHEN Country IN ('Norway', 'Norge') THEN 'NOR'
    WHEN Country IN ('Oman') THEN 'OMN'
    WHEN Country IN ('Pakistan') THEN 'PAK'
    WHEN Country IN ('Palau') THEN 'PLW'
    WHEN Country IN ('Panama') THEN 'PAN'
    WHEN Country IN ('Papua New Guinea') THEN 'PNG'
    WHEN Country IN ('Paraguay') THEN 'PRY'
    WHEN Country IN ('Peru') THEN 'PER'
    WHEN Country IN ('Philippines') THEN 'PHL'
    WHEN Country IN ('Poland', 'Polska') THEN 'POL'
    WHEN Country IN ('Portugal') THEN 'PRT'
    WHEN Country IN ('Qatar') THEN 'QAT'
    WHEN Country IN ('Romania') THEN 'ROU'
    WHEN Country IN ('Russia', 'Russian Federation', 'RU') THEN 'RUS'
    WHEN Country IN ('Rwanda') THEN 'RWA'
    WHEN Country IN ('Saint Kitts and Nevis') THEN 'KNA'
    WHEN Country IN ('Saint Lucia') THEN 'LCA'
    WHEN Country IN ('Saint Vincent and the Grenadines') THEN 'VCT'
    WHEN Country IN ('Samoa') THEN 'WSM'
    WHEN Country IN ('San Marino') THEN 'SMR'
    WHEN Country IN ('Sao Tome and Principe') THEN 'STP'
    WHEN Country IN ('Saudi Arabia') THEN 'SAU'
    WHEN Country IN ('Senegal') THEN 'SEN'
    WHEN Country IN ('Serbia') THEN 'SRB'
    WHEN Country IN ('Seychelles') THEN 'SYC'
    WHEN Country IN ('Sierra Leone') THEN 'SLE'
    WHEN Country IN ('Singapore') THEN 'SGP'
    WHEN Country IN ('Slovakia') THEN 'SVK'
    WHEN Country IN ('Slovenia') THEN 'SVN'
    WHEN Country IN ('Solomon Islands') THEN 'SLB'
    WHEN Country IN ('Somalia') THEN 'SOM'
    WHEN Country IN ('South Africa') THEN 'ZAF'
    WHEN Country IN ('South Sudan') THEN 'SSD'
    WHEN Country IN ('Spain', 'España') THEN 'ESP'
    WHEN Country IN ('Sri Lanka') THEN 'LKA'
    WHEN Country IN ('Sudan') THEN 'SDN'
    WHEN Country IN ('Suriname') THEN 'SUR'
    WHEN Country IN ('Sweden', 'Sverige') THEN 'SWE'
    WHEN Country IN ('Switzerland', 'Suisse', 'Schweiz') THEN 'CHE'
    WHEN Country IN ('Syria') THEN 'SYR'
    WHEN Country IN ('Taiwan', 'TWN') THEN 'TWN'
    WHEN Country IN ('Tajikistan') THEN 'TJK'
    WHEN Country IN ('Tanzania') THEN 'TZA'
    WHEN Country IN ('Thailand') THEN 'THA'
    WHEN Country IN ('Timor-Leste') THEN 'TLS'
    WHEN Country IN ('Togo') THEN 'TGO'
    WHEN Country IN ('Tonga') THEN 'TON'
    WHEN Country IN ('Trinidad and Tobago') THEN 'TTO'
    WHEN Country IN ('Tunisia') THEN 'TUN'
    WHEN Country IN ('Turkey') THEN 'TUR'
    WHEN Country IN ('Turkmenistan') THEN 'TKM'
    WHEN Country IN ('Tuvalu') THEN 'TUV'
    WHEN Country IN ('Uganda') THEN 'UGA'
    WHEN Country IN ('Ukraine') THEN 'UKR'
    WHEN Country IN ('United Arab Emirates') THEN 'ARE'
    WHEN Country IN ('United Kingdom', 'UK', 'Britain', 'England') THEN 'GBR'
    WHEN Country IN ('United States', 'USA', 'US') THEN 'USA'
    WHEN Country IN ('Uruguay') THEN 'URY'
    WHEN Country IN ('Uzbekistan') THEN 'UZB'
    WHEN Country IN ('Vanuatu') THEN 'VUT'
    WHEN Country IN ('Vatican City', 'Holy See') THEN 'VAT'
    WHEN Country IN ('Venezuela') THEN 'VEN'
    WHEN Country IN ('Vietnam') THEN 'VNM'
    WHEN Country IN ('Yemen') THEN 'YEM'
    WHEN Country IN ('Zambia') THEN 'ZMB'
    WHEN Country IN ('Zimbabwe') THEN 'ZWE'
    WHEN Country IN ('Hong Kong') THEN 'HKG'
    WHEN Country IN ('Israel and the Palestinian Territories') THEN 'ISR'
    WHEN Country IN ('United States of America') THEN 'USA'
    WHEN Country IN ('South Korea (Republic of Korea)') THEN 'KOR'
    WHEN Country IN ('The Gambia') THEN 'GMB'
    WHEN Country IN ("HNorth Korea (Democratic People's Republic of Korea)") THEN 'PRK'
    WHEN Country IN ('Guam') THEN 'GUM'
    WHEN Country IN ('The Republic of Slovenia') THEN 'SVN'
    WHEN Country IN ('Hong Kong') THEN 'HKG'
    WHEN Country IN ('Kosovo') THEN 'XKX'
    ELSE NULL -- Falls kein Mapping vorhanden ist
END;






###########Canada###########
UPDATE travel_advisories_can
SET Country_ISO = CASE
    WHEN Country IN ('Afghanistan') THEN 'AFG'
    WHEN Country IN ('Albania') THEN 'ALB'
    WHEN Country IN ('Algeria') THEN 'DZA'
    WHEN Country IN ('Andorra') THEN 'AND'
    WHEN Country IN ('Angola') THEN 'AGO'
    WHEN Country IN ('Antigua and Barbuda') THEN 'ATG'
    WHEN Country IN ('Argentina') THEN 'ARG'
    WHEN Country IN ('Armenia') THEN 'ARM'
    WHEN Country IN ('Australia', 'AUS') THEN 'AUS'
    WHEN Country IN ('Austria', 'Österreich') THEN 'AUT'
    WHEN Country IN ('Azerbaijan') THEN 'AZE'
    WHEN Country IN ('Bahamas') THEN 'BHS'
    WHEN Country IN ('Bahrain') THEN 'BHR'
    WHEN Country IN ('Bangladesh') THEN 'BGD'
    WHEN Country IN ('Barbados') THEN 'BRB'
    WHEN Country IN ('Belarus') THEN 'BLR'
    WHEN Country IN ('Belgium', 'België', 'Belgique') THEN 'BEL'
    WHEN Country IN ('Belize') THEN 'BLZ'
    WHEN Country IN ('Benin') THEN 'BEN'
    WHEN Country IN ('Bhutan') THEN 'BTN'
    WHEN Country IN ('Bolivia') THEN 'BOL'
    WHEN Country IN ('Bosnia and Herzegovina') THEN 'BIH'
    WHEN Country IN ('Botswana') THEN 'BWA'
    WHEN Country IN ('Brazil', 'Brasil') THEN 'BRA'
    WHEN Country IN ('Brunei') THEN 'BRN'
    WHEN Country IN ('Bulgaria') THEN 'BGR'
    WHEN Country IN ('Burkina Faso') THEN 'BFA'
    WHEN Country IN ('Burundi') THEN 'BDI'
    WHEN Country IN ('Cabo Verde') THEN 'CPV'
    WHEN Country IN ('Cambodia') THEN 'KHM'
    WHEN Country IN ('Cameroon') THEN 'CMR'
    WHEN Country IN ('Canada', 'CAN') THEN 'CAN'
    WHEN Country IN ('Central African Republic') THEN 'CAF'
    WHEN Country IN ('Chad') THEN 'TCD'
    WHEN Country IN ('Chile') THEN 'CHL'
    WHEN Country IN ('China', 'CN', 'PRC') THEN 'CHN'
    WHEN Country IN ('Colombia') THEN 'COL'
    WHEN Country IN ('Comoros') THEN 'COM'
    WHEN Country IN ('Congo (Congo-Brazzaville)') THEN 'COG'
    WHEN Country IN ('Costa Rica') THEN 'CRI'
    WHEN Country IN ('Croatia', 'Hrvatska') THEN 'HRV'
    WHEN Country IN ('Cuba') THEN 'CUB'
    WHEN Country IN ('Cyprus') THEN 'CYP'
    WHEN Country IN ('Czech Republic', 'Czechia', 'Česká republika') THEN 'CZE'
    WHEN Country IN ('Democratic Republic of the Congo') THEN 'COD'
    WHEN Country IN ('Denmark', 'Danmark') THEN 'DNK'
    WHEN Country IN ('Djibouti') THEN 'DJI'
    WHEN Country IN ('Dominica') THEN 'DMA'
    WHEN Country IN ('Dominican Republic') THEN 'DOM'
    WHEN Country IN ('Ecuador') THEN 'ECU'
    WHEN Country IN ('Egypt') THEN 'EGY'
    WHEN Country IN ('El Salvador') THEN 'SLV'
    WHEN Country IN ('Equatorial Guinea') THEN 'GNQ'
    WHEN Country IN ('Eritrea') THEN 'ERI'
    WHEN Country IN ('Estonia') THEN 'EST'
    WHEN Country IN ('Eswatini', 'Swaziland') THEN 'SWZ'
    WHEN Country IN ('Ethiopia') THEN 'ETH'
    WHEN Country IN ('Fiji') THEN 'FJI'
    WHEN Country IN ('Finland', 'Suomi') THEN 'FIN'
    WHEN Country IN ('France', 'Francia') THEN 'FRA'
    WHEN Country IN ('Gabon') THEN 'GAB'
    WHEN Country IN ('Gambia') THEN 'GMB'
    WHEN Country IN ('Georgia') THEN 'GEO'
    WHEN Country IN ('Germany', 'Deutschland') THEN 'DEU'
    WHEN Country IN ('Ghana') THEN 'GHA'
    WHEN Country IN ('Greece', 'Hellas') THEN 'GRC'
    WHEN Country IN ('Grenada') THEN 'GRD'
    WHEN Country IN ('Guatemala') THEN 'GTM'
    WHEN Country IN ('Guinea') THEN 'GIN'
    WHEN Country IN ('Guinea-Bissau') THEN 'GNB'
    WHEN Country IN ('Guyana') THEN 'GUY'
    WHEN Country IN ('Haiti') THEN 'HTI'
    WHEN Country IN ('Honduras') THEN 'HND'
    WHEN Country IN ('Hungary', 'Magyarország') THEN 'HUN'
    WHEN Country IN ('Iceland', 'Ísland') THEN 'ISL'
    WHEN Country IN ('India') THEN 'IND'
    WHEN Country IN ('Indonesia') THEN 'IDN'
    WHEN Country IN ('Iran') THEN 'IRN'
    WHEN Country IN ('Iraq') THEN 'IRQ'
    WHEN Country IN ('Ireland', 'Éire') THEN 'IRL'
    WHEN Country IN ('Israel') THEN 'ISR'
    WHEN Country IN ('Italy', 'Italia') THEN 'ITA'
    WHEN Country IN ('Jamaica') THEN 'JAM'
    WHEN Country IN ('Japan', 'Nippon') THEN 'JPN'
    WHEN Country IN ('Jordan') THEN 'JOR'
    WHEN Country IN ('Kazakhstan') THEN 'KAZ'
    WHEN Country IN ('Kenya') THEN 'KEN'
    WHEN Country IN ('Kiribati') THEN 'KIR'
    WHEN Country IN ('Korea, North', 'North Korea', 'DPRK') THEN 'PRK'
    WHEN Country IN ('Korea, South', 'South Korea', 'ROK') THEN 'KOR'
    WHEN Country IN ('Kuwait') THEN 'KWT'
    WHEN Country IN ('Kyrgyzstan') THEN 'KGZ'
    WHEN Country IN ('Laos') THEN 'LAO'
    WHEN Country IN ('Latvia') THEN 'LVA'
    WHEN Country IN ('Lebanon') THEN 'LBN'
    WHEN Country IN ('Lesotho') THEN 'LSO'
    WHEN Country IN ('Liberia') THEN 'LBR'
    WHEN Country IN ('Libya') THEN 'LBY'
    WHEN Country IN ('Liechtenstein') THEN 'LIE'
    WHEN Country IN ('Lithuania') THEN 'LTU'
    WHEN Country IN ('Luxembourg') THEN 'LUX'
    WHEN Country IN ('Madagascar') THEN 'MDG'
    WHEN Country IN ('Malawi') THEN 'MWI'
    WHEN Country IN ('Malaysia') THEN 'MYS'
    WHEN Country IN ('Maldives') THEN 'MDV'
    WHEN Country IN ('Mali') THEN 'MLI'
    WHEN Country IN ('Malta') THEN 'MLT'
    WHEN Country IN ('Marshall Islands') THEN 'MHL'
    WHEN Country IN ('Mauritania') THEN 'MRT'
    WHEN Country IN ('Mauritius') THEN 'MUS'
    WHEN Country IN ('Mexico') THEN 'MEX'
    WHEN Country IN ('Micronesia') THEN 'FSM'
    WHEN Country IN ('Moldova') THEN 'MDA'
    WHEN Country IN ('Monaco') THEN 'MCO'
    WHEN Country IN ('Mongolia') THEN 'MNG'
    WHEN Country IN ('Montenegro') THEN 'MNE'
    WHEN Country IN ('Morocco') THEN 'MAR'
    WHEN Country IN ('Mozambique') THEN 'MOZ'
    WHEN Country IN ('Myanmar', 'Burma') THEN 'MMR'
    WHEN Country IN ('Namibia') THEN 'NAM'
    WHEN Country IN ('Nauru') THEN 'NRU'
    WHEN Country IN ('Nepal') THEN 'NPL'
    WHEN Country IN ('Netherlands', 'Nederland') THEN 'NLD'
    WHEN Country IN ('New Zealand') THEN 'NZL'
    WHEN Country IN ('Nicaragua') THEN 'NIC'
    WHEN Country IN ('Niger') THEN 'NER'
    WHEN Country IN ('Nigeria') THEN 'NGA'
    WHEN Country IN ('North Macedonia') THEN 'MKD'
    WHEN Country IN ('Norway', 'Norge') THEN 'NOR'
    WHEN Country IN ('Oman') THEN 'OMN'
    WHEN Country IN ('Pakistan') THEN 'PAK'
    WHEN Country IN ('Palau') THEN 'PLW'
    WHEN Country IN ('Panama') THEN 'PAN'
    WHEN Country IN ('Papua New Guinea') THEN 'PNG'
    WHEN Country IN ('Paraguay') THEN 'PRY'
    WHEN Country IN ('Peru') THEN 'PER'
    WHEN Country IN ('Philippines') THEN 'PHL'
    WHEN Country IN ('Poland', 'Polska') THEN 'POL'
    WHEN Country IN ('Portugal') THEN 'PRT'
    WHEN Country IN ('Qatar') THEN 'QAT'
    WHEN Country IN ('Romania') THEN 'ROU'
    WHEN Country IN ('Russia', 'Russian Federation', 'RU') THEN 'RUS'
    WHEN Country IN ('Rwanda') THEN 'RWA'
    WHEN Country IN ('Saint Kitts and Nevis') THEN 'KNA'
    WHEN Country IN ('Saint Lucia') THEN 'LCA'
    WHEN Country IN ('Saint Vincent and the Grenadines') THEN 'VCT'
    WHEN Country IN ('Samoa') THEN 'WSM'
    WHEN Country IN ('San Marino') THEN 'SMR'
    WHEN Country IN ('Sao Tome and Principe') THEN 'STP'
    WHEN Country IN ('Saudi Arabia') THEN 'SAU'
    WHEN Country IN ('Senegal') THEN 'SEN'
    WHEN Country IN ('Serbia') THEN 'SRB'
    WHEN Country IN ('Seychelles') THEN 'SYC'
    WHEN Country IN ('Sierra Leone') THEN 'SLE'
    WHEN Country IN ('Singapore') THEN 'SGP'
    WHEN Country IN ('Slovakia') THEN 'SVK'
    WHEN Country IN ('Slovenia') THEN 'SVN'
    WHEN Country IN ('Solomon Islands') THEN 'SLB'
    WHEN Country IN ('Somalia') THEN 'SOM'
    WHEN Country IN ('South Africa') THEN 'ZAF'
    WHEN Country IN ('South Sudan') THEN 'SSD'
    WHEN Country IN ('Spain', 'España') THEN 'ESP'
    WHEN Country IN ('Sri Lanka') THEN 'LKA'
    WHEN Country IN ('Sudan') THEN 'SDN'
    WHEN Country IN ('Suriname') THEN 'SUR'
    WHEN Country IN ('Sweden', 'Sverige') THEN 'SWE'
    WHEN Country IN ('Switzerland', 'Suisse', 'Schweiz') THEN 'CHE'
    WHEN Country IN ('Syria') THEN 'SYR'
    WHEN Country IN ('Taiwan', 'TWN') THEN 'TWN'
    WHEN Country IN ('Tajikistan') THEN 'TJK'
    WHEN Country IN ('Tanzania') THEN 'TZA'
    WHEN Country IN ('Thailand') THEN 'THA'
    WHEN Country IN ('Timor-Leste') THEN 'TLS'
    WHEN Country IN ('Togo') THEN 'TGO'
    WHEN Country IN ('Tonga') THEN 'TON'
    WHEN Country IN ('Trinidad and Tobago') THEN 'TTO'
    WHEN Country IN ('Tunisia') THEN 'TUN'
    WHEN Country IN ('Turkey') THEN 'TUR'
    WHEN Country IN ('Turkmenistan') THEN 'TKM'
    WHEN Country IN ('Tuvalu') THEN 'TUV'
    WHEN Country IN ('Uganda') THEN 'UGA'
    WHEN Country IN ('Ukraine') THEN 'UKR'
    WHEN Country IN ('United Arab Emirates') THEN 'ARE'
    WHEN Country IN ('United Kingdom', 'UK', 'Britain', 'England') THEN 'GBR'
    WHEN Country IN ('United States', 'USA', 'US') THEN 'USA'
    WHEN Country IN ('Uruguay') THEN 'URY'
    WHEN Country IN ('Uzbekistan') THEN 'UZB'
    WHEN Country IN ('Vanuatu') THEN 'VUT'
    WHEN Country IN ('Vatican City', 'Holy See') THEN 'VAT'
    WHEN Country IN ('Venezuela') THEN 'VEN'
    WHEN Country IN ('Vietnam') THEN 'VNM'
    WHEN Country IN ('Yemen') THEN 'YEM'
    WHEN Country IN ('Zambia') THEN 'ZMB'
    WHEN Country IN ('Zimbabwe') THEN 'ZWE'
    WHEN Country IN ('Hong Kong') THEN 'HKG'
    WHEN Country IN ('Israel and the Palestinian Territories') THEN 'ISR'
    WHEN Country IN ('United States of America') THEN 'USA'
    WHEN Country IN ('South Korea (Republic of Korea)') THEN 'KOR'
    WHEN Country IN ('The Gambia') THEN 'GMB'
    WHEN Country IN ("HNorth Korea (Democratic People's Republic of Korea)") THEN 'PRK'
    WHEN Country IN ('Guam') THEN 'GUM'
    WHEN Country IN ('The Republic of Slovenia') THEN 'SVN'
    WHEN Country IN ('Hong Kong') THEN 'HKG'
    WHEN Country IN ('Kosovo') THEN 'XKX'
    WHEN Country IN ('Burma (Myanmar)') THEN 'MMR'
    WHEN Country IN ('Democratic Republic of Congo (Kinshasa)') THEN 'COD'
    WHEN Country IN ('Gibraltar') THEN 'GIB'
    WHEN Country IN ('Israel, the West Bank and the Gaza Strip') THEN 'ISR'
    WHEN Country IN ('Korea, North (DPRK)') THEN 'PRK'
    WHEN Country IN ('Kyrgyz Republic') THEN 'KGZ'
    WHEN Country IN ('Puerto Rico') THEN 'PRI'
    WHEN Country IN ('Republic of Congo (Brazzaville)') THEN 'COG'
    WHEN Country IN ('American Samoa') THEN 'ASM'
	WHEN Country IN ('Macao') THEN 'MAC'
	WHEN Country IN ('Macedonia') THEN 'MKD'
	WHEN Country IN ('Brunei Darussalam') THEN 'BRN'
    WHEN Country IN ('Gambia, The') THEN 'GMB'
    WHEN Country IN ('Brunei Darussalam') THEN 'BRN'
    ELSE NULL -- Falls kein Mapping vorhanden ist
END;



#################Germany############
use reisewarnung;
-- Neue Spalte 'Country_ISO' hinzufügen (falls noch nicht vorhanden)
ALTER TABLE travel_advisories_de
ADD COLUMN Country_ISO INT;
-- Die Spalte 'Country_ISO' basierend auf der Spalte 'country' aktualisieren
UPDATE reisewarnung.travel_advisories_de
SET Country_ISO = CASE
    WHEN country LIKE '%Afghanistan%' THEN 'AFG'
    WHEN country LIKE '%Albanien%' THEN 'ALB'
    WHEN country LIKE '%Algerien%' THEN 'DZA'
    WHEN country LIKE '%Andorra%' THEN 'AND'
    WHEN country LIKE '%Angola%' THEN 'AGO'
    WHEN country LIKE '%Antigua und Barbuda%' THEN 'ATG'
    WHEN country LIKE '%Argentinien%' THEN 'ARG'
    WHEN country LIKE '%Armenien%' THEN 'ARM'
    WHEN country LIKE '%Australien%' THEN 'AUS'
    WHEN country LIKE '%Österreich%' THEN 'AUT'
    WHEN country LIKE '%Aserbaidschan%' THEN 'AZE'
    WHEN country LIKE '%Bahamas%' THEN 'BHS'
    WHEN country LIKE '%Bahrain%' THEN 'BHR'
    WHEN country LIKE '%Bangladesch%' THEN 'BGD'
    WHEN country LIKE '%Barbados%' THEN 'BRB'
    WHEN country LIKE '%Weißrussland%' THEN 'BLR'
    WHEN country LIKE '%Belgien%' THEN 'BEL'
    WHEN country LIKE '%Belize%' THEN 'BLZ'
    WHEN country LIKE '%Benin%' THEN 'BEN'
    WHEN country LIKE '%Bhutan%' THEN 'BTN'
    WHEN country LIKE '%Bolivien%' THEN 'BOL'
    WHEN country LIKE '%Bosnien und Herzegowina%' THEN 'BIH'
    WHEN country LIKE '%Botswana%' THEN 'BWA'
    WHEN country LIKE '%Brasilien%' THEN 'BRA'
    WHEN country LIKE '%Brunei%' THEN 'BRN'
    WHEN country LIKE '%Bulgarien%' THEN 'BGR'
    WHEN country LIKE '%BurkinaFaso%' THEN 'BFA'
    WHEN country LIKE '%Burundi%' THEN 'BDI'
    WHEN country LIKE '%KapVerde%' THEN 'CPV'
    WHEN country LIKE '%Kambodscha%' THEN 'KHM'
    WHEN country LIKE '%Kamerun%' THEN 'CMR'
    WHEN country LIKE '%Kanada%' THEN 'CAN'
    WHEN country LIKE '%Zentralafrikanische Republik%' THEN 'CAF'
    WHEN country LIKE '%Tschad%' THEN 'TCD'
    WHEN country LIKE '%Chile%' THEN 'CHL'
    WHEN country LIKE '%China%' THEN 'CHN'
    WHEN country LIKE '%Kolumbien%' THEN 'COL'
    WHEN country LIKE '%Komoren%' THEN 'COM'
    WHEN country LIKE '%Kongo%' THEN 'COG'
    WHEN country LIKE '%CostaRica%' THEN 'CRI'
    WHEN country LIKE '%Kroatien%' THEN 'HRV'
    WHEN country LIKE '%Kuba%' THEN 'CUB'
    WHEN country LIKE '%Zypern%' THEN 'CYP'
    WHEN country LIKE '%Tschechien%' THEN 'CZE'
    WHEN country LIKE '%Demokratische Republik Kongo%' THEN 'COD'
    WHEN country LIKE '%Dänemark%' THEN 'DNK'
    WHEN country LIKE '%Dschibuti%' THEN 'DJI'
    WHEN country LIKE '%Dominica%' THEN 'DMA'
    WHEN country LIKE '%Dominikanische Republik%' THEN 'DOM'
    WHEN country LIKE '%Ecuador%' THEN 'ECU'
    WHEN country LIKE '%Ägypten%' THEN 'EGY'
    WHEN country LIKE '%ElSalvador%' THEN 'SLV'
    WHEN country LIKE '%Äquatorialguinea%' THEN 'GNQ'
    WHEN country LIKE '%Eritrea%' THEN 'ERI'
    WHEN country LIKE '%Estland%' THEN 'EST'
    WHEN country LIKE '%Eswatini%' THEN 'SWZ'
    WHEN country LIKE '%Äthiopien%' THEN 'ETH'
    WHEN country LIKE '%Fidschi%' THEN 'FJI'
    WHEN country LIKE '%Finnland%' THEN 'FIN'
    WHEN country LIKE '%Frankreich%' THEN 'FRA'
    WHEN country LIKE '%Gabun%' THEN 'GAB'
    WHEN country LIKE '%Gambia%' THEN 'GMB'
    WHEN country LIKE '%Georgien%' THEN 'GEO'
    WHEN country LIKE '%Deutschland%' THEN 'DEU'
    WHEN country LIKE '%Ghana%' THEN 'GHA'
    WHEN country LIKE '%Griechenland%' THEN 'GRC'
    WHEN country LIKE '%Grenada%' THEN 'GRD'
    WHEN country LIKE '%Guatemala%' THEN 'GTM'
    WHEN country LIKE '%Guinea%' THEN 'GIN'
    WHEN country LIKE '%Guinea-Bissau%' THEN 'GNB'
    WHEN country LIKE '%Guyana%' THEN 'GUY'
    WHEN country LIKE '%Haiti%' THEN 'HTI'
    WHEN country LIKE '%Honduras%' THEN 'HND'
    WHEN country LIKE '%Ungarn%' THEN 'HUN'
    WHEN country LIKE '%Island%' THEN 'ISL'
    WHEN country LIKE '%Indien%' THEN 'IND'
    WHEN country LIKE '%Indonesien%' THEN 'IDN'
    WHEN country LIKE '%Iran%' THEN 'IRN'
    WHEN country LIKE '%Irak%' THEN 'IRQ'
    WHEN country LIKE '%Irland%' THEN 'IRL'
    WHEN country LIKE '%Israel%' THEN 'ISR'
    WHEN country LIKE '%Italien%' THEN 'ITA'
    WHEN country LIKE '%Jamaika%' THEN 'JAM'
    WHEN country LIKE '%Japan%' THEN 'JPN'
    WHEN country LIKE '%Jordanien%' THEN 'JOR'
    WHEN country LIKE '%Kasachstan%' THEN 'KAZ'
    WHEN country LIKE '%Kenia%' THEN 'KEN'
    WHEN country LIKE '%Kiribati%' THEN 'KIR'
    WHEN country LIKE '%Nordkorea%' THEN 'PRK'
    WHEN country LIKE '%Südkorea%' THEN 'KOR'
    WHEN country LIKE '%Kuwait%' THEN 'KWT'
    WHEN country LIKE '%Kirgisistan%' THEN 'KGZ'
    WHEN country LIKE '%Laos%' THEN 'LAO'
    WHEN country LIKE '%Lettland%' THEN 'LVA'
    WHEN country LIKE '%Libanon%' THEN 'LBN'
    WHEN country LIKE '%Lesotho%' THEN 'LSO'
    WHEN country LIKE '%Liberia%' THEN 'LBR'
    WHEN country LIKE '%Libyen%' THEN 'LBY'
    WHEN country LIKE '%Liechtenstein%' THEN 'LIE'
    WHEN country LIKE '%Litauen%' THEN 'LTU'
    WHEN country LIKE '%Luxemburg%' THEN 'LUX'
    WHEN country LIKE '%Madagaskar%' THEN 'MDG'
    WHEN country LIKE '%Malawi%' THEN 'MWI'
    WHEN country LIKE '%Malaysia%' THEN 'MYS'
    WHEN country LIKE '%Malediven%' THEN 'MDV'
    WHEN country LIKE '%Mali%' THEN 'MLI'
    WHEN country LIKE '%Malta%' THEN 'MLT'
    WHEN country LIKE '%Marshallinseln%' THEN 'MHL'
    WHEN country LIKE '%Mauretanien%' THEN 'MRT'
    WHEN country LIKE '%Mauritius%' THEN 'MUS'
    WHEN country LIKE '%Mexiko%' THEN 'MEX'
    WHEN country LIKE '%Mikronesien%' THEN 'FSM'
    WHEN country LIKE '%Moldawien%' THEN 'MDA'
    WHEN country LIKE '%Monaco%' THEN 'MCO'
    WHEN country LIKE '%Mongolei%' THEN 'MNG'
    WHEN country LIKE '%Montenegro%' THEN 'MNE'
    WHEN country LIKE '%Marokko%' THEN 'MAR'
    WHEN country LIKE '%Mosambik%' THEN 'MOZ'
    WHEN country LIKE '%Myanmar%' THEN 'MMR'
    WHEN country LIKE '%Namibia%' THEN 'NAM'
    WHEN country LIKE '%Nauru%' THEN 'NRU'
    WHEN country LIKE '%Nepal%' THEN 'NPL'
    WHEN country LIKE '%Niederlande%' THEN 'NLD'
    WHEN country LIKE '%Neuseeland%' THEN 'NZL'
    WHEN country LIKE '%Nicaragua%' THEN 'NIC'
    WHEN country LIKE '%Niger%' THEN 'NER'
    WHEN country LIKE '%Nigeria%' THEN 'NGA'
    WHEN country LIKE '%Nordmazedonien%' THEN 'MKD'
    WHEN country LIKE '%Norwegen%' THEN 'NOR'
    WHEN country LIKE '%Oman%' THEN 'OMN'
    WHEN country LIKE '%Pakistan%' THEN 'PAK'
    WHEN country LIKE '%Palau%' THEN 'PLW'
    WHEN country LIKE '%Panama%' THEN 'PAN'
    WHEN country LIKE '%Papua-Neuguinea%' THEN 'PNG'
    WHEN country LIKE '%Paraguay%' THEN 'PRY'
    WHEN country LIKE '%Peru%' THEN 'PER'
    WHEN country LIKE '%Philippinen%' THEN 'PHL'
    WHEN country LIKE '%Polen%' THEN 'POL'
    WHEN country LIKE '%Portugal%' THEN 'PRT'
    WHEN country LIKE '%Katar%' THEN 'QAT'
    WHEN country LIKE '%Rumänien%' THEN 'ROU'
    WHEN country LIKE '%Russland%' THEN 'RUS'
    WHEN country LIKE '%Ruanda%' THEN 'RWA'
    WHEN country LIKE '%St.KittsundNevis%' THEN 'KNA'
    WHEN country LIKE '%St.Lucia%' THEN 'LCA'
    WHEN country LIKE '%St.Vincent und die Grenadinen%' THEN 'VCT'
    WHEN country LIKE '%Samoa%' THEN 'WSM'
    WHEN country LIKE '%SanMarino%' THEN 'SMR'
    WHEN country LIKE '%SãoTomé und Príncipe%' THEN 'STP'
    WHEN country LIKE '%Saudi-Arabien%' THEN 'SAU'
    WHEN country LIKE '%Senegal%' THEN 'SEN'
    WHEN country LIKE '%Serbien%' THEN 'SRB'
    WHEN country LIKE '%Seychellen%' THEN 'SYC'
    WHEN country LIKE '%SierraLeone%' THEN 'SLE'
    WHEN country LIKE '%Singapur%' THEN 'SGP'
    WHEN country LIKE '%Slowakei%' THEN 'SVK'
    WHEN country LIKE '%Slowenien%' THEN 'SVN'
    WHEN country LIKE '%Salomonen%' THEN 'SLB'
    WHEN country LIKE '%Somalia%' THEN 'SOM'
    WHEN country LIKE '%Südafrika%' THEN 'ZAF'
    WHEN country LIKE '%Südsudan%' THEN 'SSD'
    WHEN country LIKE '%Spanien%' THEN 'ESP'
    WHEN country LIKE '%SriLanka%' THEN 'LKA'
    WHEN country LIKE '%Sudan%' THEN 'SDN'
    WHEN country LIKE '%Suriname%' THEN 'SUR'
    WHEN country LIKE '%Schweden%' THEN 'SWE'
    WHEN country LIKE '%Schweiz%' THEN 'CHE'
    WHEN country LIKE '%Syrien%' THEN 'SYR'
    WHEN country LIKE '%Taiwan%' THEN 'TWN'
    WHEN country LIKE '%Tadschikistan%' THEN 'TJK'
    WHEN country LIKE '%Tansania%' THEN 'TZA'
    WHEN country LIKE '%Thailand%' THEN 'THA'
    WHEN country LIKE '%Timor-Leste%' THEN 'TLS'
    WHEN country LIKE '%Togo%' THEN 'TGO'
    WHEN country LIKE '%Tonga%' THEN 'TON'
    WHEN country LIKE '%Trinidad und Tobago%' THEN 'TTO'
    WHEN country LIKE '%Tunesien%' THEN 'TUN'
    WHEN country LIKE '%Türkei%' THEN 'TUR'
    WHEN country LIKE '%Turkmenistan%' THEN 'TKM'
    WHEN country LIKE '%Tuvalu%' THEN 'TUV'
    WHEN country LIKE '%Uganda%' THEN 'UGA'
    WHEN country LIKE '%Ukraine%' THEN 'UKR'
    WHEN country LIKE '%Vereinigte Arabische Emirate%' THEN 'ARE'
    WHEN country LIKE '%Vereinigtes Königreich%' THEN 'GBR'
    WHEN country LIKE '%Vereinigte Staaten%' THEN 'USA'
    WHEN country LIKE '%Uruguay%' THEN 'URY'
    WHEN country LIKE '%Usbekistan%' THEN 'UZB'
    WHEN country LIKE '%Vanuatu%' THEN 'VUT'
    WHEN country LIKE '%Vatikanstadt%' THEN 'VAT'
    WHEN country LIKE '%Venezuela%' THEN 'VEN'
    WHEN country LIKE '%Vietnam%' THEN 'VNM'
    WHEN country LIKE '%Jemen%' THEN 'YEM'
    WHEN country LIKE '%Sambia%' THEN 'ZMB'
    WHEN country LIKE '%Simbabwe%' THEN 'ZWE'
    WHEN country LIKE '%Belarus%' THEN 'BLR'
    WHEN country LIKE '%Costa Rica%' THEN 'CRI'
    WHEN country LIKE '%Moldau%' THEN 'MDA'
    WHEN country LIKE '%Simbabwe%' THEN 'ZWE'
    WHEN country LIKE '%El Salvador%' THEN 'SLV'
    WHEN country LIKE '%Burkina Faso%' THEN 'BFA'
    WHEN country LIKE '%Sierra Leone%' THEN 'SLE'
    ELSE NULL -- Falls kein Mapping vorhanden ist
END;


ALTER TABLE travel_advisories_de
ADD COLUMN Level_numeric INT;

-- Die neue Spalte mit den numerischen Werten basierend auf dem Mapping aktualisieren
UPDATE travel_advisories_de
SET Level_numeric = CASE
    WHEN Level = 'Teilreisewarnung' THEN 3
    WHEN Level = 'Reisewarnung' THEN 4
    WHEN Level = 'None' THEN 1
END;

############UK##############
-- Danach die Spalte basierend auf den Bedingungen aktualisieren
use reisewarnung;
ALTER TABLE travel_advisories_uk
ADD COLUMN Level_numeric INT;

-- Danach die Spalte basierend auf den Bedingungen aktualisieren
UPDATE travel_advisories_uk
SET Level_numeric = CASE
    WHEN Advice LIKE '%against%' AND Advice LIKE '%essential%' THEN 3
    WHEN Advice LIKE '%against%' THEN 4
    ELSE 1
END;